version: '3'

services:
  catalog-service:
    image: vishwacloudlab/catalog-service
    ports: 
     - "80:80"
  redis:
    image: redis:alpine
  review-service:
    image: vishwacloudlab/review-service
    ports:
    - "90:90"
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.01'
          memory: 50M
        reservations:
          cpus: '0.001'
          memory: 20M
  order-service:
    image: vishwacloudlab/order-service
    ports:
    - "95:95"
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.01'
          memory: 50M
        reservations:
          cpus: '0.001'
          memory: 20M

